### ISSUE TITLE
[1.11.2] Some kind of conflict with Scannable mod

### ISSUE THREAD

**Issue by jesmores** [the-realest-stu/Rustic#10]
I dropped the shiny new version of Rustic 0.3 on my custom modpack and world chunks suddently stop loading. You get all the way to actually loading the world, but there's nothing in it, just void. Inventory works, but you're just stuck there and can't move and there is only emptiness. This applies to both existing and new worlds.

When I made a little test pack with just Rustic, world seems to load just fine, so I spent some time trying to narrow down which other mod was causing a bad interaction and I found out it was the Scannable mod (link below).

I'm not sure if it's your or Scannable's fault, I will open a corresponding issue on Scannable as well.

Scannable mod: https://minecraft.curseforge.com/projects/scannable
Minecraft Log: https://gist.github.com/jesmores/ae0246c6bb2c4ebf5e191c90308a3bc6

This part looks particularly interesting

```
java.lang.IllegalArgumentException: Cannot set property PropertyEnum{name=axis, clazz=class net.minecraft.util.EnumFacing$Axis, values=[x, z]} to y on block rustic:grape_leaves, it is not an allowed value
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177226_a(BlockStateContainer.java:227) ~[atm$a.class:?]
	at rustic.common.blocks.crops.BlockGrapeLeaves.func_180651_a(BlockGrapeLeaves.java:99) ~[BlockGrapeLeaves.class:?]
	at li.cil.scannable.client.scanning.ScanResultProviderBlock.buildOreCache(ScanResultProviderBlock.java:434) ~[ScanResultProviderBlock.class:?]
	at li.cil.scannable.client.scanning.ScanResultProviderBlock.rebuildOreCache(ScanResultProviderBlock.java:88) ~[ScanResultProviderBlock.class:?]
	at li.cil.scannable.common.config.Settings.setServerSettings(Settings.java:232) ~[Settings.class:?]
	at li.cil.scannable.client.network.handler.MessageHandlerConfig.onMessage(MessageHandlerConfig.java:15) ~[MessageHandlerConfig.class:?]
	at li.cil.scannable.client.network.handler.MessageHandlerConfig.onMessage(MessageHandlerConfig.java:11) ~[MessageHandlerConfig.class:?]
```

**Comment by the-realest-stu** [comment]
The problem was on my end. Thanks for reporting that!

I fixed it and just submitted an update to curseforge!

**Comment by jesmores** [comment]
Thanks, I will check again once I get my hands on the new version.

**Comment by jesmores** [comment]
Yup, world loads fine now, thanks!
