### ISSUE TITLE
[1.12.2] Server crash when using crushing basin

### ISSUE THREAD

**Issue by MilesCharman** [the-realest-stu/Rustic#145]
I have an unexpected issue with my server crashing when I attempt to use the crushing basin on honeycombs. My theory is it's a mod conflict with Biomes O' Plenty. Does anyone know a fix?

> ---- Minecraft Crash Report ----
> 
> WARNING: coremods are present:
>   IELoadingPlugin (ImmersiveEngineering-0.12-76-core.jar)
>   LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
>   AppleCore (AppleCore-mc1.12.2-3.1.1.jar)
> Contact their authors BEFORE contacting forge
> 
> // Daisy, daisy...
> 
> Time: 2/19/18 7:31 AM
> Description: Exception ticking world
> 
> java.lang.NullPointerException: Null string not allowed
> 	at java.util.Objects.requireNonNull(Unknown Source)
> 	at net.minecraft.nbt.NBTTagString.<init>(NBTTagString.java:19)
> 	at net.minecraft.nbt.NBTTagCompound.func_74778_a(NBTTagCompound.java:137)
> 	at net.minecraftforge.fluids.FluidStack.writeToNBT(FluidStack.java:108)
> 	at net.minecraftforge.fluids.FluidTank.writeToNBT(FluidTank.java:77)
> 	at net.minecraftforge.fluids.capability.TileFluidHandler.func_189515_b(TileFluidHandler.java:47)
> 	at rustic.common.tileentity.TileEntityCrushingTub.func_189515_b(TileEntityCrushingTub.java:203)
> 	at rustic.common.tileentity.TileEntityCrushingTub.func_189517_E_(TileEntityCrushingTub.java:179)
> 	at rustic.common.tileentity.TileEntityCrushingTub.func_189518_D_(TileEntityCrushingTub.java:185)
> 	at net.minecraft.server.management.PlayerChunkMapEntry.func_187273_a(PlayerChunkMapEntry.java:288)
> 	at net.minecraft.server.management.PlayerChunkMapEntry.func_187280_d(PlayerChunkMapEntry.java:250)
> 	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:115)
> 	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754)
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
> 	at java.lang.Thread.run(Unknown Source)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Server thread
> Stacktrace:
> 	at java.util.Objects.requireNonNull(Unknown Source)
> 	at net.minecraft.nbt.NBTTagString.<init>(NBTTagString.java:19)
> 	at net.minecraft.nbt.NBTTagCompound.func_74778_a(NBTTagCompound.java:137)
> 	at net.minecraftforge.fluids.FluidStack.writeToNBT(FluidStack.java:108)
> 	at net.minecraftforge.fluids.FluidTank.writeToNBT(FluidTank.java:77)
> 	at net.minecraftforge.fluids.capability.TileFluidHandler.func_189515_b(TileFluidHandler.java:47)
> 	at rustic.common.tileentity.TileEntityCrushingTub.func_189515_b(TileEntityCrushingTub.java:203)
> 	at rustic.common.tileentity.TileEntityCrushingTub.func_189517_E_(TileEntityCrushingTub.java:179)
> 	at rustic.common.tileentity.TileEntityCrushingTub.func_189518_D_(TileEntityCrushingTub.java:185)
> 	at net.minecraft.server.management.PlayerChunkMapEntry.func_187273_a(PlayerChunkMapEntry.java:288)
> 	at net.minecraft.server.management.PlayerChunkMapEntry.func_187280_d(PlayerChunkMapEntry.java:250)
> 	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:115)
> 	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
> 
> -- Affected level --
> Details:
> 	Level name: world
> 	All players: 1 total; [EntityPlayerMP['JackdawGrey'/6005, l='world', x=197.57, y=67.56, z=253.64]]
> 	Chunk stats: ServerChunkCache: 441 Drop: 0
> 	Level seed: -1802706081896451000
> 	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
> 	Level generator options: 
> 	Level spawn location: World: (172,64,256), Chunk: (at 12,4,0 in 10,16; contains blocks 160,0,256 to 175,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
> 	Level time: 124900 game time, 150515 day time
> 	Level dimension: 0
> 	Level storage version: 0x04ABD - Anvil
> 	Level weather: Rain time: 112681 (now: false), thunder time: 73240 (now: false)
> 	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
> Stacktrace:
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754)
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
> 	at java.lang.Thread.run(Unknown Source)
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.12.2
> 	Operating System: Windows 10 (amd64) version 10.0
> 	Java Version: 1.8.0_151, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 2389553000 bytes (2278 MB) / 3195535360 bytes (3047 MB) up to 3195535360 bytes (3047 MB)
> 	JVM Flags: 2 total; -Xmx3G -Xms3G
> 	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
> 	FML: MCP 9.42 Powered by Forge 14.23.2.2618 23 mods loaded, 23 mods active
> 	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
> 
> 	| State     | ID                   | Version      | Source                                        | Signature                                |
> 	|:--------- |:-------------------- |:------------ |:--------------------------------------------- |:---------------------------------------- |
> 	| UCHIJAAAA | minecraft            | 1.12.2       | minecraft.jar                                 | None                                     |
> 	| UCHIJAAAA | mcp                  | 9.42         | minecraft.jar                                 | None                                     |
> 	| UCHIJAAAA | FML                  | 8.0.99.99    | forge-1.12.2-14.23.2.2618-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
> 	| UCHIJAAAA | forge                | 14.23.2.2618 | forge-1.12.2-14.23.2.2618-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
> 	| UCHIJAAAA | biomesoplenty        | 7.0.1.2302   | BiomesOPlenty-1.12.2-7.0.1.2302-universal.jar | None                                     |
> 	| UCHIJAAAA | craftstudioapi       | 1.0.0        | CraftStudio-1.0.0.93-mc1.12-alpha.jar         | None                                     |
> 	| UCHIJAAAA | animania             | 1.4.5        | animania-1.12.2-1.4.5.jar                     | None                                     |
> 	| UCHIJAAAA | antiqueatlas         | 4.4.6        | antiqueatlas-1.12.2-4.4.6.jar                 | None                                     |
> 	| UCHIJAAAA | examplemod           | 1.0          | antiqueatlas-1.12.2-4.4.6.jar                 | None                                     |
> 	| UCHIJAAAA | applecore            | 3.1.1        | AppleCore-mc1.12.2-3.1.1.jar                  | None                                     |
> 	| UCHIJAAAA | jei                  | 4.8.5.147    | jei_1.12.2-4.8.5.147.jar                      | None                                     |
> 	| UCHIJAAAA | appleskin            | 1.0.9        | AppleSkin-mc1.12-1.0.9.jar                    | None                                     |
> 	| UCHIJAAAA | fairylights          | 2.1.2        | fairylights-2.1.2-1.12.x.jar                  | None                                     |
> 	| UCHIJAAAA | hardcoredarkness     | 2.0          | HardcoreDarkness-MC1.12.2-2.0.jar             | d72e0dd57935b3e9476212aea0c0df352dd76291 |
> 	| UCHIJAAAA | waila                | 1.8.23       | Hwyla-1.8.23-B38_1.12.jar                     | None                                     |
> 	| UCHIJAAAA | immersiveengineering | 0.12-76      | ImmersiveEngineering-0.12-76.jar              | 4cb49fcde3b43048c9889e0a3d083225da926334 |
> 	| UCHIJAAAA | immersivepetroleum   | @VERSION@    | immersivepetroleum-1.12.2-1.1.7.jar           | None                                     |
> 	| UCHIJAAAA | radixcore            | 1.12.x-2.2.1 | RadixCore-1.12.x-2.2.1-universal.jar          | None                                     |
> 	| UCHIJAAAA | mca                  | 1.12.2-5.3.1 | MCA-1.12.x-5.3.1-universal.jar                | None                                     |
> 	| UCHIJAAAA | roots                | 0.104        | roots-2-0.104.jar                             | None                                     |
> 	| UCHIJAAAA | rustic               | 0.4.8        | rustic-0.4.8.jar                              | None                                     |
> 	| UCHIJAAAA | spiceoflife          | 1.3.11       | SpiceOfLife-mc1.12-1.3.11.jar                 | None                                     |
> 	| UCHIJAAAA | twilightforest       | 3.6.345      | twilightforest-1.12.2-3.6.345-universal.jar   | None                                     |
> 
> 	Loaded coremods (and transformers): 
> IELoadingPlugin (ImmersiveEngineering-0.12-76-core.jar)
>   blusunrize.immersiveengineering.common.asm.IEClassTransformer
> LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
>   lumien.hardcoredarkness.asm.ClassTransformer
> AppleCore (AppleCore-mc1.12.2-3.1.1.jar)
>   squeek.applecore.asm.TransformerModuleHandler
> 	Profiler Position: N/A (disabled)
> 	Player Count: 1 / 20; [EntityPlayerMP['JackdawGrey'/6005, l='world', x=197.57, y=67.56, z=253.64]]
> 	Is Modded: Definitely; Server brand changed to 'fml,forge'
> 	Type: Dedicated Server  (map_server.txt)

[crash-2018-02-19_07.31.23-server.txt](https://github.com/the-realest-stu/Rustic/files/1736723/crash-2018-02-19_07.31.23-server.txt)

**Comment by the-realest-stu** [comment]
I haven't been able to reproduce this bug, but I think I've managed to track down the issue from the crash report, and I just did something that should fix it. I plan on releasing an update with this fix and more within a day or two.
