### ISSUE TITLE
Rustic Brewing

### ISSUE THREAD

**Issue by Fortist** [the-realest-stu/Rustic#241]
For some reason, whenever you look up fluids in certain ways for the brewing barrel, the recipe disappears in JEI and this gets thrown in the log.

```
[00:47:10] [Client thread/ERROR] [jei]: Error caught from Recipe Category: rustic.compat.jei.BrewingRecipeCategory
java.lang.NullPointerException: null
	at mezz.jei.plugins.vanilla.ingredients.fluid.FluidStackHelper.getMatch(FluidStackHelper.java:27) ~[FluidStackHelper.class:?]
	at mezz.jei.plugins.vanilla.ingredients.fluid.FluidStackHelper.getMatch(FluidStackHelper.java:22) ~[FluidStackHelper.class:?]
	at mezz.jei.gui.ingredients.GuiIngredient.getMatch(GuiIngredient.java:151) ~[GuiIngredient.class:?]
	at mezz.jei.gui.ingredients.GuiIngredient.set(GuiIngredient.java:108) ~[GuiIngredient.class:?]
	at mezz.jei.gui.ingredients.GuiIngredientGroup.set(GuiIngredientGroup.java:118) ~[GuiIngredientGroup.class:?]
	at rustic.compat.jei.BrewingRecipeCategory.setRecipe(BrewingRecipeCategory.java:83) ~[BrewingRecipeCategory.class:?]
	at mezz.jei.gui.recipes.RecipeLayout.create(RecipeLayout.java:69) [RecipeLayout.class:?]
	at mezz.jei.gui.recipes.RecipeGuiLogic.getRecipeLayouts(RecipeGuiLogic.java:198) [RecipeGuiLogic.class:?]
	at mezz.jei.gui.recipes.RecipesGui.updateLayout(RecipesGui.java:477) [RecipesGui.class:?]
	at mezz.jei.gui.recipes.RecipesGui.onStateChange(RecipesGui.java:523) [RecipesGui.class:?]
	at mezz.jei.gui.recipes.RecipeGuiLogic.setRecipeCategory(RecipeGuiLogic.java:231) [RecipeGuiLogic.class:?]
	at mezz.jei.gui.recipes.RecipeCategoryTab.handleMouseClicked(RecipeCategoryTab.java:33) [RecipeCategoryTab.class:?]
	at mezz.jei.gui.recipes.RecipeGuiTabs.handleMouseClicked(RecipeGuiTabs.java:133) [RecipeGuiTabs.class:?]
	at mezz.jei.gui.recipes.RecipesGui.mouseClicked(RecipesGui.java:318) [RecipesGui.class:?]
	at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:533) [blk.class:?]
	at mezz.jei.gui.recipes.RecipesGui.handleMouseInput(RecipesGui.java:298) [RecipesGui.class:?]
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:501) [blk.class:?]
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1759) [bib.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098) [bib.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:3942) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_181]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_181]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

**Comment by the-realest-stu** [comment]
Fixed in version 1.1.0
