### ISSUE TITLE
cabinet renderer crash

### ISSUE THREAD

**Issue by Sirplop** [the-realest-stu/Rustic#39]
Description: Rendering Block Entity

java.lang.IllegalArgumentException: Cannot get property PropertyBool{name=top, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:209)
	at rustic.client.renderer.CabinetRenderer.renderTileEntityAt(CabinetRenderer.java:32)
	at rustic.client.renderer.CabinetRenderer.func_180535_a(CabinetRenderer.java:16)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:173)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:146)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:999)
	at shadersmod.client.ShadersRender.renderShadowMap(ShadersRender.java:372)
	at shadersmod.client.Shaders.beginRender(Shaders.java:4097)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1569)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1361)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Welp. Doesn't happen without the shaders, and happens on all versions that have shadows. (tested on v1.141 and v1.163 of Sildur's)

**Comment by jeep70** [comment]
Me and my friends are getting this without shaders installed
https://gist.github.com/jeep70/69a5bfc3070879afa58be8538df8a186

**Comment by the-realest-stu** [comment]
@Sirplop What version of rustic?

**Comment by Sirplop** [comment]
@the-realest-stu using Rustic 0.3.5. Going to test 0.3.6 to see if it still happens.

**Comment by the-realest-stu** [comment]
Can you post the crash log? This really shouldn't be happening, but I have seen it before. I just forgot to save the log, and haven't seen it since? Do you know of a way to trigger the crash?

**Comment by Sirplop** [comment]
Sure thing!
https://gist.github.com/Sirplop/45f5fb7f783e7c56c8fc3652fd794d12
It always triggers whenever I break the cabinet with the shaders on, but the cabinet is broken when the world is reloaded.

**Comment by the-realest-stu** [comment]
Huh. So shaders do actually effect this. Good to know. I'll see what I can do.

Thanks so much, though, now I can actually test this to see if things I try actually work.

**Comment by the-realest-stu** [comment]
Fixed! I just uploaded an update to curseforge, should be available a few minutes after I post this.
