### ISSUE TITLE
Crash with grape leaves

### ISSUE THREAD

**Issue by gchpaco** [the-realest-stu/Rustic#44]
Experienced a crash while not doing anything in particular, while my grapes were growing.  Relevant backtrace:

// Quite honestly, I wouldn't worry myself about that.

Time: 6/19/17 2:12 PM
Description: Exception while ticking a block

java.lang.NoClassDefFoundError: net/minecraft/world/World$2
	at net.minecraft.world.World.func_190524_a(World.java:549)
	at net.minecraft.world.World.func_175685_c(World.java:484)
	at net.minecraft.world.World.func_175722_b(World.java:432)
	at net.minecraft.world.World.markAndNotifyBlock(World.java:373)
	at net.minecraft.world.World.func_180501_a(World.java:353)
	at rustic.common.blocks.crops.BlockGrapeLeaves.func_180650_b(BlockGrapeLeaves.java:266)
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:745)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:217)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:748)

I ... can't put it past Forge being buggy.  Running 2315.

[crash-2017-06-19_14.12.21-server.txt](https://github.com/the-realest-stu/Rustic/files/1086075/crash-2017-06-19_14.12.21-server.txt)

**Comment by gchpaco** [comment]
My partner on this server suggest that http://www.minecraftforge.net/forum/topic/23262-1710solved-javalangnoclassdeffounderror-netminecraftworldworld2/ may be relevant.

**Comment by gchpaco** [comment]
Re: setup: I had an active IE coke oven next to one of the stake+rope blocks at the end of the grapes.  Moving it to see if it mitigates.

**Comment by the-realest-stu** [comment]
I'll look into this next time I work on Rustic (probably this weekend, or early next week).

**Comment by the-realest-stu** [comment]
I rewrote how grape leaves and ropes and such update, so this should be fixed in 0.4, which was just released.
