### ISSUE TITLE
NullpointerException spam after placing down brewing barrel.

### ISSUE THREAD

**Issue by Lordician** [the-realest-stu/Rustic#67]
Hi there.
I would like to report an issue with the brewing barrel.
Right after i place it, my log/command prompt (running a server with rustic) gets spammed with this nullpointer exception:
`
[22:18:07] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_144]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_144]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:679) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
`
It is a very generic exception so i am not 100% sure what is causing it.
The exception is constantly spammed, multiple times a second after placing the barrel down.
I will post a log later that is more condensed (i was runnign a server for quite long with quite some mods and chatting).
Minecraft version 1.11.2
Forge version 1.11.2-forge1.11.2-13.20.1.2414
Mod version 0.3.12
I am posting this before i can post a log to see if this is a known issue somehow or if anyone else had this issue.
The log will come a tiny bit later.

**Comment by Lordician** [comment]
Here is both the log from my client and FML (to see the mod setup).
[logs.zip](https://github.com/the-realest-stu/Rustic/files/1188813/logs.zip)
I should probably try this out with less mods and see if it applies without other mods as well.

**Comment by Lordician** [comment]
After a lot of testing and adding and removing mods, i found out that the mod Hwyla-1.8.17-B31_1.11 is causing my issue.
This is a fork of/alternative to WAILA (What Am I Looking At).
WAILA does not cause the same issue, so i suppose for me, the best answer is to go back to WAILA.
I suppose i should put in an issue with HWYLA about this issue.

**Comment by TehNut** [comment]
The logic in `hasCapability` and `getCapability` do not match and break contract. If you return true in `has`, you need to not return `null` in `get`.

**Comment by the-realest-stu** [comment]
I'll fix this and release a small update.

**Comment by the-realest-stu** [comment]
Uploaded the update to curseforge, should be available there soon.
